version: '3.9'
services:
  database:
    image: 'postgres:15.2'
    ports:
      - '25432:5432'
    environment:
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: 'dpage/pgadmin4:latest'
    ports:
      - '8082:80'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@admin.com'
      - 'PGADMIN_DEFAULT_PASSWORD=root'
    volumes:
      - pgdata:/var/lib/pgadmin
volumes:
  postgres:
  pgdata: